spring:
  application:
    name: eureka-server
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false